version: 1

loggers:
  root:
    level: WARNING
    handlers:
      - json_handler
  feed_downloader:
    level: DEBUG
    handlers:
      - json_handler
    propagate: false

formatters:
  json_formatter:
    "()": "pythonjsonlogger.jsonlogger.JsonFormatter"
    format: "%(levelname)s %(asctime)s %(name)s %(message)s %(pathname)s %(lineno)d %(exc_info)s"

handlers:
  json_handler:
    class: logging.StreamHandler
    formatter: json_formatter
